import type { SectionTemplate } from "../../core/entities/SectionTemplate";

export const sectionTemplates: SectionTemplate[] = [
  {
    id: "template-simple-navbar",
    name: "Simple Navbar",
    description: "Logo, navigation links, and action button.",
    category: "navigation",
    section: {
      id: "section-root",
      name: "Simple Navbar",
      width: 760,
      height: 72,
      backgroundColor: "#ffffff",
      borderColor: "#cbd5e1",
      borderWidth: 1,
      borderRadius: 12,
      elements: [
        {
          id: "template-navbar-logo",
          type: "text",
          name: "Logo",
          x: 24,
          y: 24,
          width: 120,
          height: 24,
          text: "Brand",
          backgroundColor: "transparent",
          textColor: "#0f172a",
          borderColor: "transparent",
          borderWidth: 0,
          borderRadius: 0,
        },
        {
          id: "template-navbar-link-home",
          type: "text",
          name: "Home Link",
          x: 280,
          y: 26,
          width: 60,
          height: 20,
          text: "Home",
          backgroundColor: "transparent",
          textColor: "#334155",
          borderColor: "transparent",
          borderWidth: 0,
          borderRadius: 0,
        },
        {
          id: "template-navbar-link-about",
          type: "text",
          name: "About Link",
          x: 360,
          y: 26,
          width: 70,
          height: 20,
          text: "About",
          backgroundColor: "transparent",
          textColor: "#334155",
          borderColor: "transparent",
          borderWidth: 0,
          borderRadius: 0,
        },
        {
          id: "template-navbar-link-contact",
          type: "text",
          name: "Contact Link",
          x: 450,
          y: 26,
          width: 80,
          height: 20,
          text: "Contact",
          backgroundColor: "transparent",
          textColor: "#334155",
          borderColor: "transparent",
          borderWidth: 0,
          borderRadius: 0,
        },
        {
          id: "template-navbar-button",
          type: "button",
          name: "Action Button",
          x: 620,
          y: 18,
          width: 112,
          height: 36,
          text: "Get started",
          backgroundColor: "#2563eb",
          textColor: "#ffffff",
          borderColor: "#1d4ed8",
          borderWidth: 1,
          borderRadius: 8,
        },
      ],
    },
  },
  {
    id: "template-topbar-search",
    name: "Topbar Search",
    description: "Compact topbar with title, search input, and button.",
    category: "navigation",
    section: {
      id: "section-root",
      name: "Topbar Search",
      width: 760,
      height: 64,
      backgroundColor: "#f8fafc",
      borderColor: "#cbd5e1",
      borderWidth: 1,
      borderRadius: 10,
      elements: [
        {
          id: "template-topbar-title",
          type: "text",
          name: "Title",
          x: 20,
          y: 22,
          width: 160,
          height: 24,
          text: "Dashboard",
          backgroundColor: "transparent",
          textColor: "#0f172a",
          borderColor: "transparent",
          borderWidth: 0,
          borderRadius: 0,
        },
        {
          id: "template-topbar-search",
          type: "input",
          name: "Search Input",
          x: 250,
          y: 14,
          width: 300,
          height: 36,
          placeholder: "Search...",
          backgroundColor: "#ffffff",
          textColor: "#0f172a",
          borderColor: "#cbd5e1",
          borderWidth: 1,
          borderRadius: 8,
        },
        {
          id: "template-topbar-button",
          type: "button",
          name: "Search Button",
          x: 570,
          y: 14,
          width: 120,
          height: 36,
          text: "Search",
          backgroundColor: "#0f172a",
          textColor: "#ffffff",
          borderColor: "#0f172a",
          borderWidth: 1,
          borderRadius: 8,
        },
      ],
    },
  },
  {
    id: "template-login-form",
    name: "Login Form",
    description: "Email input, password input, remember checkbox, and submit button.",
    category: "form",
    section: {
      id: "section-root",
      name: "Login Form",
      width: 360,
      height: 280,
      backgroundColor: "#ffffff",
      borderColor: "#cbd5e1",
      borderWidth: 1,
      borderRadius: 16,
      elements: [
        {
          id: "template-login-title",
          type: "text",
          name: "Title",
          x: 24,
          y: 24,
          width: 220,
          height: 28,
          text: "Sign in",
          backgroundColor: "transparent",
          textColor: "#0f172a",
          borderColor: "transparent",
          borderWidth: 0,
          borderRadius: 0,
        },
        {
          id: "template-login-email",
          type: "input",
          name: "Email Input",
          x: 24,
          y: 72,
          width: 312,
          height: 38,
          placeholder: "Email",
          backgroundColor: "#ffffff",
          textColor: "#0f172a",
          borderColor: "#cbd5e1",
          borderWidth: 1,
          borderRadius: 8,
        },
        {
          id: "template-login-password",
          type: "input",
          name: "Password Input",
          x: 24,
          y: 124,
          width: 312,
          height: 38,
          placeholder: "Password",
          backgroundColor: "#ffffff",
          textColor: "#0f172a",
          borderColor: "#cbd5e1",
          borderWidth: 1,
          borderRadius: 8,
        },
        {
          id: "template-login-remember",
          type: "checkbox",
          name: "Remember Checkbox",
          x: 24,
          y: 174,
          width: 180,
          height: 24,
          text: "Remember me",
          backgroundColor: "transparent",
          textColor: "#334155",
          borderColor: "transparent",
          borderWidth: 0,
          borderRadius: 0,
        },
        {
          id: "template-login-submit",
          type: "button",
          name: "Submit Button",
          x: 24,
          y: 220,
          width: 312,
          height: 40,
          text: "Sign in",
          backgroundColor: "#2563eb",
          textColor: "#ffffff",
          borderColor: "#1d4ed8",
          borderWidth: 1,
          borderRadius: 8,
        },
      ],
    },
  },
  {
    id: "template-contact-form",
    name: "Contact Form",
    description: "Simple contact form with name, email, and message placeholder.",
    category: "form",
    section: {
      id: "section-root",
      name: "Contact Form",
      width: 420,
      height: 330,
      backgroundColor: "#ffffff",
      borderColor: "#cbd5e1",
      borderWidth: 1,
      borderRadius: 16,
      elements: [
        {
          id: "template-contact-title",
          type: "text",
          name: "Title",
          x: 24,
          y: 24,
          width: 260,
          height: 28,
          text: "Contact us",
          backgroundColor: "transparent",
          textColor: "#0f172a",
          borderColor: "transparent",
          borderWidth: 0,
          borderRadius: 0,
        },
        {
          id: "template-contact-name",
          type: "input",
          name: "Name Input",
          x: 24,
          y: 72,
          width: 372,
          height: 38,
          placeholder: "Name",
          backgroundColor: "#ffffff",
          textColor: "#0f172a",
          borderColor: "#cbd5e1",
          borderWidth: 1,
          borderRadius: 8,
        },
        {
          id: "template-contact-email",
          type: "input",
          name: "Email Input",
          x: 24,
          y: 124,
          width: 372,
          height: 38,
          placeholder: "Email",
          backgroundColor: "#ffffff",
          textColor: "#0f172a",
          borderColor: "#cbd5e1",
          borderWidth: 1,
          borderRadius: 8,
        },
        {
          id: "template-contact-message",
          type: "box",
          name: "Message Box",
          x: 24,
          y: 176,
          width: 372,
          height: 82,
          backgroundColor: "#f8fafc",
          textColor: "#0f172a",
          borderColor: "#cbd5e1",
          borderWidth: 1,
          borderRadius: 8,
        },
        {
          id: "template-contact-submit",
          type: "button",
          name: "Submit Button",
          x: 24,
          y: 278,
          width: 372,
          height: 40,
          text: "Send message",
          backgroundColor: "#2563eb",
          textColor: "#ffffff",
          borderColor: "#1d4ed8",
          borderWidth: 1,
          borderRadius: 8,
        },
      ],
    },
  },
  {
    id: "template-button-group",
    name: "Button Group",
    description: "Three horizontal action buttons.",
    category: "controls",
    section: {
      id: "section-root",
      name: "Button Group",
      width: 420,
      height: 72,
      backgroundColor: "#ffffff",
      borderColor: "#cbd5e1",
      borderWidth: 1,
      borderRadius: 12,
      elements: [
        {
          id: "template-button-primary",
          type: "button",
          name: "Primary Button",
          x: 20,
          y: 18,
          width: 120,
          height: 36,
          text: "Primary",
          backgroundColor: "#2563eb",
          textColor: "#ffffff",
          borderColor: "#1d4ed8",
          borderWidth: 1,
          borderRadius: 8,
        },
        {
          id: "template-button-secondary",
          type: "button",
          name: "Secondary Button",
          x: 150,
          y: 18,
          width: 120,
          height: 36,
          text: "Secondary",
          backgroundColor: "#ffffff",
          textColor: "#334155",
          borderColor: "#cbd5e1",
          borderWidth: 1,
          borderRadius: 8,
        },
        {
          id: "template-button-cancel",
          type: "button",
          name: "Cancel Button",
          x: 280,
          y: 18,
          width: 120,
          height: 36,
          text: "Cancel",
          backgroundColor: "#f8fafc",
          textColor: "#334155",
          borderColor: "#cbd5e1",
          borderWidth: 1,
          borderRadius: 8,
        },
      ],
    },
  },
];